# Generated by Django 4.2.6 on 2024-09-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image_url', models.TextField(blank=True)),
                ('image_width', models.CharField(blank=True, max_length=10)),
                ('image_height', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
