# Generated by Django 4.2.6 on 2025-04-18 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_image_height_alter_person_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_sub', models.CharField(max_length=255, unique=True)),
                ('is_private_email', models.BooleanField(default=False)),
                ('real_user_status', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apple_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
