# Generated by Django 4.2.6 on 2024-09-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boulder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.SmallIntegerField(default=1)),
                ('suggested_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.SmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boulder.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'boulder'], name='send_send_person__4196f9_idx')],
            },
        ),
    ]
