# Generated by Django 4.2.6 on 2024-09-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image_url', models.TextField(blank=True)),
                ('image_width', models.CharField(blank=True, max_length=10)),
                ('image_height', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('matching', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=True)),
                ('feet_follow_hands', models.BooleanField(default=True)),
                ('kickboard_on', models.BooleanField(default=False)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sends_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.TextField()),
                ('image_width', models.CharField(default=1000, max_length=10)),
                ('image_height', models.CharField(default=1000, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_ascensionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_ascended_boulders', to=settings.AUTH_USER_MODEL)),
                ('setter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_boulders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprayWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('image_width', models.CharField(default=1000, max_length=10)),
                ('image_height', models.CharField(default=1000, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.SmallIntegerField(default=1)),
                ('suggested_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.SmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('private', models.BooleanField(default=False)),
                ('boulders', models.ManyToManyField(related_name='circuits', to='climbers_eye_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spraywall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.spraywall')),
            ],
        ),
        migrations.AddField(
            model_name='boulder',
            name='spraywall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.spraywall'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('other_info', models.CharField(blank=True, max_length=100, null=True)),
                ('bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.bookmark')),
                ('boulder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.boulder')),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.circuit')),
                ('like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.like')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.send')),
                ('spraywall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbers_eye_backend.spraywall')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbers_eye_backend.gym'),
        ),
        migrations.AddIndex(
            model_name='send',
            index=models.Index(fields=['person', 'boulder'], name='climbers_ey_person__316226_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('person', 'boulder')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('person', 'boulder')},
        ),
    ]
