# Generated by Django 4.2.6 on 2024-09-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spraywall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('matching', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=True)),
                ('feet_follow_hands', models.BooleanField(default=True)),
                ('kickboard_on', models.BooleanField(default=False)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sends_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.TextField()),
                ('image_width', models.CharField(default=1000, max_length=10)),
                ('image_height', models.CharField(default=1000, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_ascensionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_ascended_boulders', to=settings.AUTH_USER_MODEL)),
                ('setter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_boulders', to=settings.AUTH_USER_MODEL)),
                ('spraywall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spraywall.spraywall')),
            ],
        ),
    ]
