# Generated by Django 4.2.6 on 2025-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='alt_wall_image_url',
            field=models.TextField(blank=True, help_text='Alternative image of the default spray wall for this particular boulder.', null=True),
        ),
    ]
