# Generated by Django 4.2.6 on 2025-05-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0002_boulder_alt_wall_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='Thumbnail image for boulder.', null=True),
        ),
    ]
