# Generated by Django 4.2.6 on 2025-05-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0003_boulder_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boulder',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='boulder',
            name='alt_wall_thumbnail_url',
            field=models.TextField(blank=True, help_text='Alternative spray wall image thumbnail for boulder.', null=True),
        ),
    ]
