# Generated by Django 4.2.6 on 2025-06-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0004_remove_boulder_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='grade',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
