# Generated by Django 4.2.6 on 2024-09-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spraywall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boulder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('private', models.BooleanField(default=False)),
                ('boulders', models.ManyToManyField(related_name='circuits', to='boulder.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spraywall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spraywall.spraywall')),
            ],
        ),
    ]
