# Generated by Django 4.2.6 on 2024-09-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('image_width', models.CharField(default=1000, max_length=10)),
                ('image_height', models.CharField(default=1000, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
        ),
    ]
