# Generated by Django 4.2.6 on 2025-05-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spraywall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spraywall',
            name='thumbnail_image_url',
            field=models.TextField(default='https://climberseye.s3.us-west-1.amazonaws.com/thumbnail/Face-92767fc7-00b8-4c58-bb31-ec6b888dfcfa.jpg'),
            preserve_default=False,
        ),
    ]
