# Generated by Django 4.2.1 on 2023-05-17 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='spray_backend/files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='SprayWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_data', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('setter_name', models.CharField(max_length=100)),
                ('first_ascent_name', models.CharField(max_length=100)),
                ('sends', models.IntegerField()),
                ('image_data', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('spraywall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.spraywall')),
            ],
        ),
    ]
