# Generated by Django 4.2.1 on 2023-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulder',
            old_name='image_data',
            new_name='boulder_image_data',
        ),
        migrations.RenameField(
            model_name='spraywall',
            old_name='image_data',
            new_name='spraywall_image_data',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='first_ascent_name',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='setter_name',
        ),
        migrations.AddField(
            model_name='boulder',
            name='boulder_image_height',
            field=models.CharField(default=1000, max_length=10),
        ),
        migrations.AddField(
            model_name='boulder',
            name='boulder_image_width',
            field=models.CharField(default=1000, max_length=10),
        ),
        migrations.AddField(
            model_name='boulder',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spraywall',
            name='spraywall_image_height',
            field=models.CharField(default=1000, max_length=10),
        ),
        migrations.AddField(
            model_name='spraywall',
            name='spraywall_image_width',
            field=models.CharField(default=1000, max_length=10),
        ),
    ]
