# Generated by Django 4.2.1 on 2023-05-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0002_rename_image_data_boulder_boulder_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profile_image_data', models.TextField(blank=True)),
                ('profile_image_width', models.CharField(blank=True, default=1000, max_length=10)),
                ('profile_image_height', models.CharField(blank=True, default=1000, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.gym')),
                ('spraywall', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.spraywall')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.person')),
            ],
            options={
                'unique_together': {('person', 'boulder')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.person')),
            ],
            options={
                'unique_together': {('person', 'boulder')},
            },
        ),
    ]
