# Generated by Django 4.2.1 on 2023-05-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0003_person_send_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.gym'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image_height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image_width',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='spraywall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.spraywall'),
        ),
    ]
