# Generated by Django 4.2.1 on 2023-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0007_alter_boulder_spraywall_alter_spraywall_gym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulder',
            old_name='rating',
            new_name='quality',
        ),
        migrations.AddField(
            model_name='send',
            name='attempts',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='send',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='send',
            name='quality',
            field=models.SmallIntegerField(default=3),
        ),
    ]
