# Generated by Django 4.2.1 on 2023-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0008_rename_rating_boulder_quality_send_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
