# Generated by Django 4.2.1 on 2023-05-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0009_send_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulder',
            old_name='sends',
            new_name='sends_count',
        ),
    ]
