# Generated by Django 4.2.1 on 2023-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0011_remove_send_attempts_remove_send_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='attempts',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='send',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='send',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='send',
            name='quality',
            field=models.SmallIntegerField(default=3),
        ),
    ]
