# Generated by Django 4.2.1 on 2023-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0013_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
