# Generated by Django 4.2.1 on 2023-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0015_circuit_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.boulder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.person')),
            ],
            options={
                'unique_together': {('person', 'boulder')},
            },
        ),
    ]
