# Generated by Django 4.2.1 on 2023-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0016_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banner_image_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='banner_image_height',
            field=models.CharField(blank=True, default=1000, max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='banner_image_width',
            field=models.CharField(blank=True, default=1000, max_length=10),
        ),
    ]
