# Generated by Django 4.2.1 on 2023-06-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0017_person_banner_image_data_person_banner_image_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile_image_data',
            new_name='headshot_image_data',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='profile_image_height',
            new_name='headshot_image_height',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='profile_image_width',
            new_name='headshot_image_width',
        ),
    ]
