# Generated by Django 4.2.1 on 2023-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0018_rename_profile_image_data_person_headshot_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RenameField(
            model_name='boulder',
            old_name='boulder_image_data',
            new_name='boulder_image_url',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='banner_image_data',
            new_name='banner_image_url',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='headshot_image_data',
            new_name='headshot_image_url',
        ),
        migrations.RenameField(
            model_name='spraywall',
            old_name='spraywall_image_data',
            new_name='spraywall_image_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spraywall',
        ),
    ]
