# Generated by Django 4.2.1 on 2023-07-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0019_cat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
