# Generated by Django 4.2.1 on 2023-08-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0020_delete_cat_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='first_ascent_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_ascent_person', to='spray_backend.person'),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='setter_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setter_person', to='spray_backend.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spray_backend.gym'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spray_backend.person')),
                ('spraywall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.spraywall')),
            ],
        ),
    ]
