# Generated by Django 4.2.1 on 2023-08-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0021_alter_boulder_first_ascent_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
