# Generated by Django 4.2.1 on 2023-08-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0022_alter_activity_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='message',
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='other_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.activity'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.activity'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.activity'),
        ),
        migrations.AddField(
            model_name='like',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.activity'),
        ),
        migrations.AddField(
            model_name='send',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.activity'),
        ),
    ]
