# Generated by Django 4.2.1 on 2023-08-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0024_remove_bookmark_activity_remove_boulder_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='banner_image_height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='banner_image_width',
        ),
    ]
