# Generated by Django 4.2.1 on 2023-08-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0027_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spray_backend.circuit'),
        ),
    ]
