# Generated by Django 4.2.1 on 2023-09-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0028_activity_circuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulder',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='sends_count',
        ),
        migrations.AddField(
            model_name='boulder',
            name='feet_follow_hands',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boulder',
            name='kickboard_on',
            field=models.BooleanField(default=False),
        ),
    ]
