# Generated by Django 4.2.1 on 2023-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0029_rename_description_boulder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='sends_count',
            field=models.IntegerField(default=0),
        ),
    ]
