# Generated by Django 4.2.1 on 2023-09-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0030_boulder_sends_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulder',
            old_name='notes',
            new_name='description',
        ),
    ]
