# Generated by Django 4.2.1 on 2023-09-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0032_alter_send_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='sends_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
