# Generated by Django 4.2.1 on 2023-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray_backend', '0033_alter_boulder_sends_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
