# Generated by Django 4.2.6 on 2024-12-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='type',
            new_name='classification',
        ),
    ]
