# Generated by Django 4.2.6 on 2024-12-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_type_gym_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='classification',
            new_name='type',
        ),
    ]
